In [45]:
1/2

0.5

In [46]:
s="abcderf"

In [47]:
s[3:6]

'der'

In [48]:
[1,2,3,4]

[1, 2, 3, 4]

In [49]:
import numpy as np

In [50]:
my_list=[[1,4,32],[1,4,32],[1,4,32]]

In [51]:
arr = np.array(my_list)

In [52]:
arr

array([[ 1,  4, 32],
       [ 1,  4, 32],
       [ 1,  4, 32]])

In [53]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [54]:
np.zeros(5)

array([ 0.,  0.,  0.,  0.,  0.])

In [132]:
np.ones(3)

array([ 1.,  1.,  1.])

In [56]:
np.linspace(0,5,7)

array([ 0.        ,  0.83333333,  1.66666667,  2.5       ,  3.33333333,
        4.16666667,  5.        ])

In [165]:
np.eye(3)

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

In [58]:
np.random.rand(5)

array([ 0.97229065,  0.18264933,  0.6902007 ,  0.54188291,  0.87318874])

In [59]:
np.random.randint(1,5,10)

array([1, 2, 1, 1, 1, 2, 1, 1, 4, 4])

In [138]:
arr = np.arange(25)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [139]:
ranarr = np.random.randint(0,20,10)

In [140]:
ranarr

array([10,  7,  3,  5,  9, 18,  6,  1, 15,  4])

In [141]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [142]:
arr.max()

24

In [143]:
arr.min()

0

In [144]:
arr.argmax()


24

In [145]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [146]:
arr.dtype

dtype('int64')

In [147]:
ranarr.dtype

dtype('int64')

In [148]:
ranarr

array([10,  7,  3,  5,  9, 18,  6,  1, 15,  4])

In [151]:
arr[4] #4th number

4

In [73]:
ranarr[1:5]

array([10, 13, 18, 14])

In [154]:
slice_arr = arr[0:6]

In [155]:
slice_arr

array([0, 1, 2, 3, 4, 5])

In [76]:
slice_arr[:]=99

In [77]:
slice_arr

array([99, 99, 99, 99, 99, 99])

In [78]:
ranarr

array([12, 10, 13, 18, 14,  1,  9, 10,  4,  1])

In [79]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [86]:
arr_2d = np.array([[1,10,4],[2,13,4],[1,2,3]])
arr_2d

array([[ 1, 10,  4],
       [ 2, 13,  4],
       [ 1,  2,  3]])

In [164]:
arr_2d * np.array([[3,3,3],[2,5,1],[3,0,2]])

array([[ 3, 30, 12],
       [ 4, 65,  4],
       [ 3,  0,  6]])

In [88]:
arr_2d[arr_2d>10]

array([13])

In [89]:
arr_2d_ = np.arange(90).reshape(9,10) 

In [90]:
arr_2d_

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89]])

In [91]:
arr_2d_[4:6,4:6]

array([[44, 45],
       [54, 55]])

In [179]:
arr_2d.shape

(3, 3)

In [175]:
#numpy operation

In [176]:
np.sqrt(arr_2d)

array([[ 1.        ,  3.16227766,  2.        ],
       [ 1.41421356,  3.60555128,  2.        ],
       [ 1.        ,  1.41421356,  1.73205081]])

In [177]:
np.exp(arr_2d)

array([[  2.71828183e+00,   2.20264658e+04,   5.45981500e+01],
       [  7.38905610e+00,   4.42413392e+05,   5.45981500e+01],
       [  2.71828183e+00,   7.38905610e+00,   2.00855369e+01]])

In [186]:
np.ones(10) * 5 #ex_10_fives

array([ 5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.])

In [174]:
np.arange(0.01,1.01,0.01).reshape(10,10) #exercise

array([[ 0.01,  0.02,  0.03,  0.04,  0.05,  0.06,  0.07,  0.08,  0.09,  0.1 ],
       [ 0.11,  0.12,  0.13,  0.14,  0.15,  0.16,  0.17,  0.18,  0.19,  0.2 ],
       [ 0.21,  0.22,  0.23,  0.24,  0.25,  0.26,  0.27,  0.28,  0.29,  0.3 ],
       [ 0.31,  0.32,  0.33,  0.34,  0.35,  0.36,  0.37,  0.38,  0.39,  0.4 ],
       [ 0.41,  0.42,  0.43,  0.44,  0.45,  0.46,  0.47,  0.48,  0.49,  0.5 ],
       [ 0.51,  0.52,  0.53,  0.54,  0.55,  0.56,  0.57,  0.58,  0.59,  0.6 ],
       [ 0.61,  0.62,  0.63,  0.64,  0.65,  0.66,  0.67,  0.68,  0.69,  0.7 ],
       [ 0.71,  0.72,  0.73,  0.74,  0.75,  0.76,  0.77,  0.78,  0.79,  0.8 ],
       [ 0.81,  0.82,  0.83,  0.84,  0.85,  0.86,  0.87,  0.88,  0.89,  0.9 ],
       [ 0.91,  0.92,  0.93,  0.94,  0.95,  0.96,  0.97,  0.98,  0.99,  1.  ]])

In [192]:
np.arange(1,101).reshape(10,10)/100

array([[ 0.01,  0.02,  0.03,  0.04,  0.05,  0.06,  0.07,  0.08,  0.09,  0.1 ],
       [ 0.11,  0.12,  0.13,  0.14,  0.15,  0.16,  0.17,  0.18,  0.19,  0.2 ],
       [ 0.21,  0.22,  0.23,  0.24,  0.25,  0.26,  0.27,  0.28,  0.29,  0.3 ],
       [ 0.31,  0.32,  0.33,  0.34,  0.35,  0.36,  0.37,  0.38,  0.39,  0.4 ],
       [ 0.41,  0.42,  0.43,  0.44,  0.45,  0.46,  0.47,  0.48,  0.49,  0.5 ],
       [ 0.51,  0.52,  0.53,  0.54,  0.55,  0.56,  0.57,  0.58,  0.59,  0.6 ],
       [ 0.61,  0.62,  0.63,  0.64,  0.65,  0.66,  0.67,  0.68,  0.69,  0.7 ],
       [ 0.71,  0.72,  0.73,  0.74,  0.75,  0.76,  0.77,  0.78,  0.79,  0.8 ],
       [ 0.81,  0.82,  0.83,  0.84,  0.85,  0.86,  0.87,  0.88,  0.89,  0.9 ],
       [ 0.91,  0.92,  0.93,  0.94,  0.95,  0.96,  0.97,  0.98,  0.99,  1.  ]])

In [187]:
np.random.randn(25) # 25 random number sample form standard deviation

array([-2.69557787,  1.03992519, -1.1399116 , -0.12802891,  0.18941041,
       -0.65284336, -1.36357463, -0.90395164,  0.57376811,  1.45306288,
       -0.97730142, -1.04877209, -0.64554392, -1.43375395,  1.16033476,
        0.57896256,  0.24704551,  0.95096637,  0.33124475, -0.03083358,
        0.07323438,  1.36238137,  1.30397702, -2.16156426, -1.77099633])

In [102]:
ex_array = np.arange(1,26).reshape(5,5)

In [109]:
ex_array

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [105]:
ex_array[2:5, 1:5]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [108]:
ex_array[3, 4]

20

In [110]:
ex_array[0:3,1:2]

array([[ 2],
       [ 7],
       [12]])

In [111]:
ex_array[4:5,0:5]

array([[21, 22, 23, 24, 25]])

In [112]:
ex_array[3:5,0:5]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [194]:
ex_array.sum()

325

In [196]:
ex_array.std()

7.2111025509279782

In [118]:
sum(ex_array)

array([55, 60, 65, 70, 75])

In [200]:
ex_array.sum(axis=0)

array([55, 60, 65, 70, 75])